[package]
name = "mcospkg"
version = "0.1.0"
authors = ["zhangxuan2011 <zx20110412@outlook.com>"]
edition = "2021"

[package.metadata]
license = "GPL-3.0"
repository = "https://github.com/zhangxuan2011/mcospkg"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
colored = "2.2.0"
pyo3 = { version = "0.23.3", features = ["auto-initialize"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# This is the binary file define area
# The file format: mcospkg-xxx
# Filename: src/xxx.rs
[[bin]]
name = "mcospkg-mirror"
path = "src/mirror.rs"

[[bin]]
name = "mcospkg-info"
path = "src/info.rs"
